APP_TITLE = "Options Scalper Dashboard"

INDEX_LIST = ["NIFTY", "SENSEX"]
OPTION_TYPES = ["CE", "PE"]
MODES = ["AUTO", "MANUAL", "BACKTEST"]
DATA_SOURCES = ["LIVE", "HISTORICAL"]

LOT_SIZES = {
    "NIFTY": 75,
    "SENSEX": 20,
}

EMA_FAST = 9
EMA_SLOW = 21
DEFAULT_TARGET_POINTS = 45
DEFAULT_SL_POINTS = 12
DEFAULT_LOTS = 1

SQUAREOFF_HOUR = 15
SQUAREOFF_MINUTE = 15

LOOKBACK_DAYS = 20
CANDLE_INTERVAL = "5min"